version: '3.8'

services:
  redis:
    image: redis/redis-stack
    volumes:
      - redis_data:/data:rw
    ports:
      - 6379:6379
    restart: unless-stopped


volumes:
  redis_data:
    driver: local